# Pytorch Blitz - Pytorch Tensors (250615.4)

https://docs.pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [3]:
import torch
import numpy as np

A tensor is just a matrix. 

You can make tensors/matrices from Python arrays using the `torch.tensor` class or from Numpay arrays the `torch.from_numpy` class 

In [10]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data) 
x_data

tensor([[1, 2],
        [3, 4]])

In [12]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [11]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2997, 0.3384],
        [0.1528, 0.7128]]) 

