# Pytorch Blitz - Pytorch Tensors (250615.4)

https://docs.pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [3]:
import torch
import numpy as np

A tensor is just a matrix. 

You can make tensors/matrices from Python arrays using the `torch.tensor` class. Or the the `torch.from_numpy` class using Numpay arrays.

In [10]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data) 
x_data

tensor([[1, 2],
        [3, 4]])

In [12]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

Calling the `.shape` attribute on the tensor object gives the dimensions of the matrix. 

Format is in [rows, columns] 

In [15]:
x_np.shape

torch.Size([2, 2])

In [16]:
data = [[1, 2, 3], [3, 4, 5]]
x2_data = torch.tensor(data) 
x2_data

tensor([[1, 2, 3],
        [3, 4, 5]])

In [17]:
x2_data.shape

torch.Size([2, 3])

### Why did NumPy not support matrices like Pytorch tensors? (250615.5)

Numpy *does* do matrices. The NumPy `ndarray` can be n-dimensional (n = number of columns). BUT they live in the RAM/CPU only.

In Pytorch, every `tensor` supports many devices (GPU, CPU, others). Each `tensor` object is aware of the device it is running on. You can see this with the `.device` attribute/flag.

In [18]:
x2_data.device

device(type='cpu')

Example of moving a `tensor` object from cpu to a gpu: https://colab.research.google.com/drive/1V9X9je2illJSHYUHDhBeQQyhA6c8W7gg?usp=sharing

Also unlike NumPy `ndarray`, tensor operations can be chained and remembered. Outside of the output, operations on `ndarray` are not remembered/stored. 

This "chain" allows `tensor` to do automatic differentiation / backprop / `autograd`. The next tutorial will go over this.